# Generated by Django 4.2.7 on 2023-11-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('DateStart', models.DateTimeField(default=0)),
                ('DateEnd', models.DateTimeField(default=0)),
                ('budget', models.IntegerField(default=0)),
                ('findingSource', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('capture', 'capture'), ('utilization', 'utilization'), ('T&S', 'T&S'), ('Full Chain', 'Full Chain')], max_length=15)),
                ('TRLSart', models.IntegerField(default=0)),
                ('TRLend', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('EmissionsDecrease', models.FloatField(default=0)),
                ('label', models.IntegerField(choices=[('0', '0'), ('1', '1')], default=0)),
            ],
        ),
    ]
