# Generated by Django 4.2.7 on 2023-11-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='label',
        ),
        migrations.AlterField(
            model_name='approvals',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='findingSource',
            field=models.FloatField(default=0),
        ),
    ]
